taskName: testTasks
targetAttributes: [userid]
targetLowMetrics: [data_count_minutes]
targetHighMetrics: []

dbUrl: postgres
baseQuery: SELECT * FROM mapmatch_history H, sf_datasets D WHERE H.dataset_id = D.id LIMIT 10000;

logging:
  level: INFO

  loggers:
    "macrobase": TRACE